- include: common/main.yml
- include: apt/main.yml
- include: os_account/main.yml
- include: ovs_int/main.yml
- include: ovs_ext/main.yml
- include: nic/main.yml
- include: nic_ext/main.yml
- include: set_vars/main.yml
- include: ntp/main.yml
- include: ntpdate/main.yml
- include: mysql/main.yml
- include: rabbitmq/main.yml
- include: memcached/main.yml
- include: keystone/main.yml
- include: glance/main.yml
- include: cinder/main.yml
- include: quantum/main.yml
- include: nova/main.yml
- include: horizon/main.yml
